export const PARIX_AGENT_SKILL = [
  '---',
  'name: parix',
  'description: "Operate Parix through the `parix` CLI: inspect authentication and active organization context, manage database lifecycle, call authenticated Parix API endpoints, and run TigerBeetle queries or mutations. Use for Parix CLI setup, sessions, database catalog/list/info/create/remove work, Parix API requests, and TigerBeetle account or transfer operations."',
  '---',
  '',
  '# Parix CLI',
  '',
  'Use the installed `parix` binary. Prefer scoped `--help` over guessing flags.',
  '',
  '## Start safely',
  '',
  '1. Run `command -v parix`. If it is absent, ask the user to install it with `npm install -g @parix/cli`.',
  '2. Run `parix auth status` before authenticated work. Confirm the base URL and active organization before any mutation. Status may refresh and persist tokens or organization context, so it is not strictly read-only. If no usable session exists, ask the user to complete `parix auth login`; login opens a browser OAuth flow.',
  '3. Treat `https://parix.io` as production. Login resolves its target as explicit `--base-url`, then `PARIX_BASE_URL`, then production; it ignores any URL in the stored session. Later commands resolve explicit URL, then stored URL, then environment, then production. Pass `--base-url <url>` explicitly when the environment matters.',
  '4. Use `parix database`, not `parix db`; no `db` alias exists.',
  '',
  'Never read or print `~/.config/parix/session.json`; it contains access and refresh tokens.',
  '',
  '`parix auth logout` deletes the local session without confirmation; run it only when explicitly requested.',
  '',
  '## Discover before changing state',
  '',
  '```bash',
  'parix database catalog',
  'parix database list',
  'parix database info <database-id>',
  'parix database <command> --help',
  'parix tb <command> --help',
  '```',
  '',
  'Database and TigerBeetle commands operate in the active organization from the current session. Stop if that organization or target environment is not the intended one.',
  '',
  'Use `--json` when a database or TigerBeetle command needs the complete response, but do not assume it is directly pipeable to `jq`: current output is wrapped by Clack formatting.',
  '',
  '## Manage databases',
  '',
  '- Run `parix database catalog` before creation and use provider, region, cluster, size, and storage identifiers returned by it.',
  '- Treat `parix database create` as potentially billable. Run it only when the user explicitly requests the exact resource. `--storage-gb` must be a positive integer.',
  '- Inspect the create response, including `success`, billing, and provisioning fields; exit code 0 alone does not prove provisioning started. Only when `success` is true and a database ID is returned, follow with `parix database info <database-id>`.',
  '- Treat `parix database remove <database-id>` as destructive. Resolve the exact ID, obtain explicit confirmation, and only then use `--yes` for a non-interactive run. Removal is queued; verify the returned workflow/status rather than claiming immediate deletion.',
  '',
  '## Run TigerBeetle operations',
  '',
  'Read operations are `lookup-accounts`, `lookup-transfers`, `get-account-transfers`, `get-account-balances`, `query-accounts`, and `query-transfers`. `create-accounts` and `create-transfers` mutate data; run them only when explicitly requested.',
  '',
  'Choose exactly one payload style:',
  '',
  '- flags for a single/common operation;',
  "- `--payload '<json>'` for raw JSON; or",
  '- `--file <path>` for a JSON file.',
  '',
  '`--file` takes precedence over `--payload`, and either raw form bypasses flag-built payloads, defaults, and validation. Flag-built account creation requires `--ledger` and `--code`. Ordinary transfer creation requires `--from`, `--to`, `--amount`, `--ledger`, and `--code`. Post-pending transfer creation requires `--flag post_pending_transfer`, `--pending-id`, and `--amount`; debit/credit IDs, ledger, and code may be omitted to inherit them. Void-pending transfer creation requires `--flag void_pending_transfer` and `--pending-id`; amount and the same inherited fields may be omitted. Imported accounts and transfers also require `--timestamp` in nanoseconds, greater than 0 and less than 2^63; nonzero `--timeout` values are in seconds and limited to non-imported pending transfers. Linked batches require `--payload` or `--file`.',
  '',
  'Supply stable explicit `--id` values for retryable mutations; omitted IDs are newly generated on each run. Flag-built queries and account filters default to `--limit 100`.',
  '',
  'Newly provisioned databases may not be ready immediately. Check `parix database info` and retry read-only readiness checks before TigerBeetle mutations.',
  '',
  '## Call the authenticated API',
  '',
  '```bash',
  'parix api /api/v1/session',
  'parix api /api/v1/example -X POST -d \'{"key":"value"}\'',
  '```',
  '',
  "Prefer relative `/api/...` paths. An absolute HTTP(S) URL also receives the stored bearer token, so use one only when the user explicitly trusts that host. Repeat `-H 'name:value'` for headers; a body defaults to `content-type: application/json` unless overridden.",
  '',
  'Always inspect the printed HTTP status. `parix api` and `parix tb` set a non-zero exit code on HTTP 4xx/5xx; still read the body for `detail` and `tbResults`.',
  '',
  '## Verify outcomes',
  '',
  'Report the target base URL and organization, the exact command class used, the response status/body, and any asynchronous provisioning or deletion state. Do not infer success from process exit alone.',
  '',
].join('\n');
